import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"77",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/77.mp3?alt=media&token=83596866-fae3-47b1-b6fc-8f6b26b34fb0",
            active: true,
        },
        {
            name:"amg",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://mp3.chillhop.com/serve.php/?mp3=22794",
            active: false,
        },
        {
            name:"bye",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"chanel",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming.hotmixradio.fm/hotmixradio-80-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"delivery",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: " http://streaming.hotmixradio.fr/hotmixradio-lounge-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"el azul",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://mp3.ffh.de/ffhchannels/hq90er.mp3?amsparams=playerid:RTFFHTunein;skey:1581676248",
            active: false,
        },
        {
            name:"el belicon",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq?sABC=5r46783o%230%231o70r21o79929956s30p83402120q5q4%23gharva&amsparams=playerid:tunein;skey:1581676603",
            active: false,
        },
        {
            name:"el gavilan",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://cob-ais.leanstream.co/CINDFM-MP3?args=tunein_01",
            active: false,
        },
        {
            name:"ella baila sola",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://los.cdnstream.com/1102_128",
            active: false,
        },
        {
            name:"gavilan ll",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://listen-funkids.sharp-stream.com/funkids.mp3?device=tunein",
            active: false,
        },
        {
            name:"igualito a mi apa",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.cdm-chillout.com:8020/stream-mp3-Chill",
            active: false,
        },
        {
            name:"la bebe",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTgxNjc3NjI5LCJ0ZC1yZWciOmZhbHNlfQ.OMSwENr75iagPVR3nvwThrfNUw1lLuC7x1jCWc5qOAo",
            active: false,
        },
        {
            name:"lagunas",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.soundstorm-radio.com:8000/stream1",
            active: false,
        },
        {
            name:"las morras",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"nueva vida",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.defjay.com/DEFJAY.mp3",
            active: false,
        },
        {
            name:"plebada",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"prc",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://fm02-ice.stream.khz.se/fm02_mp3",
            active: false,
        },
        {
            name:"rosa pastel",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cms.stream.publicradio.org/cms.mp3?aw_0_1st.playerid=RadioTime&aw_0_1st.skey=1582304573&aw_0_1st.platform=tunein",
            active: false,
        },
        {
            name:"rubicon",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://mainstream.amazingradios.com:8000/blues128",
            active: false,
        },
        {
            name:"sentosa",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live-radio02.mediahubaustralia.com/JAZW/mp3/",
            active: false,
        },
        {
            name:"siempre pendientes",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
        {
            name:"su casa",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://pureplay.cdnstream1.com/6011_128.mp3",
            active: true,
        },
        {
            name:"tulum",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://mp3.chillhop.com/serve.php/?mp3=22794",
            active: false,
        },
        {
            name:"vvs",
            artist: "PP",
            cover: "https://firebasestorage.googleapis.com/v0/b/pesoplumamusic.appspot.com/o/p.p..png?alt=media&token=170b6635-e01c-4fb1-b68e-40c9b8bd2f3f",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },    
    ];
}

export default chillHop;

